# Generated by Django 4.1.4 on 2022-12-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_car_image_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.car'),
        ),
    ]
